### ISSUE TITLE
The repository url in package.json is incorrect

### ISSUE THREAD

**Issue by CaselIT** [Daplie/greenlock-express#102]
Just seen it while checking the library on npm.

**Comment by coolaj86** [comment]
https://www.npmjs.com/package/greenlock-express lists https://git.daplie.com/Daplie/greenlock-express which is the correct url.

Unless you mean that it is missing `.git`, which I've noted https://git.daplie.com/Daplie/greenlock-express/issues/116 and that should be corrected.

Thanks!

**Comment by CaselIT** [comment]
It was an old issue. Thanks for closing it.
