### ISSUE TITLE
port is overritten if plainPort is falsey

### ISSUE THREAD

**Issue by WORMSS** [Daplie/greenlock-express#104]
`port` is overritten if `plainPort` is falsey

https://github.com/Daplie/letsencrypt-express/blob/master/lex.js#L26

eg, `listen(0, 3001)` becomes `80` and `443`

**Comment by coolaj86** [comment]
Hmmm... a use case I hadn't considered.

Shall we check `isNaN()` then?

**Comment by WORMSS** [comment]
Just checking each variable separately should be fine.
