### ISSUE TITLE
Strange error with letsencrypt-express

### ISSUE THREAD

**Issue by davidnagli** [Daplie/greenlock-express#107]
I have been experiencing a strange error with letsencrypt-express where whenever I attempt to run it locally and go to the port all I see is:
```

Hello, World!
With Love,
Let's Encrypt Express

```
It used to work perfectly fine, but this suddenly appeared. The strange part is that when I run the exact same code on my server it works perfectly (my server and local machine both use the same OS; Ubuntu)

I originally thought that the issue was caused by the fact that I requested to many certificates and reached my monthly quota. However, after more than 2 months of halted development I am still experiencing this issue.

I have the issue when using the staging and non-staging servers. I use the same OS and OS version on my local machine and server, and I'm running the exact same code. It's also nothing wrong with my express routes, since everything works perfectly when I run it locally using `app.listen()` without any SSL.

In case this helps the problem get resolved faster, the response I'm seeing comes from this part from the beginning of letsencrypt-express/lex.js

``` javascript
opts.app = opts.app || function (req, res) {
    res.end("Hello, World!\nWith Love,\nLet's Encrypt Express");
};
```

**Comment by coolaj86** [comment]
I only provide the oversimplified example in the README for the purpose of illustration. If you read a little further down the "advanced" usage is the more meaningful usage.

However, what you're seeing there is that `opts.app` was not passed in from the function in which you are creating it.

https://git.daplie.com/Daplie/greenlock-express/blob/master/lex.js#L4

Literally if you were to `console.log(opts)` that you are passing in you would see that `opts.app` is undefined.

If you still need help with this please re-open the issue on https://git.daplie.com/Daplie/greenlock-express
