### ISSUE TITLE
trouble with certificate on angular app

### ISSUE THREAD

**Issue by nirdil** [Daplie/greenlock-express#118]
Hi,
I'm using the mean stack (mongo, express, angular, node).
I've been trying to get my app to run over https.
I managed to get a valid certificate using the following code:

    var lex = require('greenlock-express').create({
        server: 'https://acme-v01.api.letsencrypt.org/directory'
         , email: 'xxx@yyy.com'
         , agreeTos: true
         , approvedDomains: [ 'my.domain.net' ]
         , debug: true
    });
    require('http').createServer(lex.middleware(require('redirect-https')())).listen(80, function () {
        console.log("Listening for ACME http-01 challenges on", this.address());
    });

    require('https').createServer(lex.httpsOptions, lex.middleware(app)).listen(443, function () {
        console.log("Listening for ACME tls-sni-01 challenges and serve app on", this.address());
    });

it seems to be working fine, here are the results i get when launching the server:

    le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed
    [le/lib/middleware.js] created middleware
    Listening for ACME http-01 challenges on { address: '::', family: 'IPv6', port: 80 }
    Listening for ACME tls-sni-01 challenges and serve app on { address: '::', family: 'IPv6', port: 443 }
    [le/index.js] le.getCertificates called for my.domain.net with certs for NONE
    [le/index.js] le.approveDomains called with certs for NONE and options:
    [le/index.js] { domain: 'my.domain.net', 
        domains: [ 'my.domain.net' ],
        email: 'xxx@yyy.com',
        agreeTos: true }
    [le/index.js] le getting from disk or registering new
    [le/lib/core.js] checkAsync found existing certificates
    [le/lib/core.js] Check Expires At 2018-05-07T16:09:27.000Z
    [le/lib/core.js] Check Renewable At 2018-04-30T16:09:27.000Z
    [le/lib/middleware.js] no match, skipping middleware
    [le/lib/middleware.js] no match, skipping middleware

now, if i try to load to the browser some static resource on my server that my app uses, it works great, chrome says the connection is secured.
But, if when i try load my angular app itself, the app gets served under an https url, but the browser says its not a secure connection.
two things to note-
1. I keep getting lots of those `[le/lib/middleware.js] no match, skipping middleware` messages.
2. the `.loopback should be defined as function` might be a problem?

**Comment by nirdil** [comment]
This seems to be related to a bug on my side at the end. The library works great.

**Comment by pavelbinar** [comment]
@nirdil I am getting a lot of `[le/lib/middleware.js] no match, skipping middleware` as well, do remember, where was the issue?

**Comment by coolaj86** [comment]
This fork is not the official repo and is not maintained.

Please see the docs and screencast at the official repository:
https://git.coolaj86.com/coolaj86/greenlock-express.js

Every common troubleshooting issue is covered in the screencast.

**Comment by pavelbinar** [comment]
@coolaj86 All right, thanks.
