### ISSUE TITLE
Handle server with http2 and lex middleware

### ISSUE THREAD

**Issue by skaltenegger** [Daplie/greenlock-express#127]
Hi there, 

First of all, great work of you, so much appreciated!

After searching a lot in this repo's issues and on Google I couldn't find out how to run the server with http2 (of course secure with secure https) instead of simple https over http1.1

Could you provide me with a code sample of how I need to change the following so that it works with Node's built in http2 module but still secure with the lex middleware? 
```
require('https').createServer(lex.httpsOptions, lex.middleware(server)).listen(443, function () {
  console.log("Listening for ACME tls-sni-01 challenges and serve app on", this.address());
});
```

You help is very much appreciated!
Thanks a lot in advance,
Stefan

**Comment by coolaj86** [comment]
@skaltenegger Would you mind closing this issue?

**Comment by coolaj86** [comment]
@skaltenegger Would you mind closing this issue? so that the STICKY issue about the official repo stays on top?
