### ISSUE TITLE
Wildcard SSL still not working.

### ISSUE THREAD

**Issue by archiebaer** [Daplie/greenlock-express#132]
I am using this:
```js
require('greenlock-express').create({
  server: 'https://acme-staging-v02.api.letsencrypt.org/directory',
  version: 'draft-11',
  email: 'archie@serveradmin.xyz',
  agreeTos: true,
  approveDomains: ['*.keytap.xyz'],
  logRejectedDomains: false,
  app: app
}).listen(80, 443);
```

and I get the error:
```
Unhandled rejection Error: invalid SNI
    at gl.tlsOptions.SNICallback (/keytap/node_modules/greenlock/index.js:502:12)
    at Object.greenlock.tlsOptions.SNICallback (/keytap/node_modules/greenlock-express/index.js:128:7)
    at /keytap/node_modules/greenlock-express/index.js:79:34
    at Promise._execute (/keytap/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/keytap/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/keytap/node_modules/bluebird/js/release/promise.js:79:10)
    at /keytap/node_modules/greenlock-express/index.js:77:18
    at tryCatcher (/keytap/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/keytap/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/keytap/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/keytap/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/keytap/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/keytap/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/keytap/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/keytap/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/keytap/node_modules/bluebird/js/release/promise.js:569:18)
```

I've been searching for hours, but I can't find any examples with wildcards. I'm on version 2.6.7. I assume I'll have to use DNS verification for it also, but I can't figure that out.

If you could help, I would really appreciate it. I would like to finish this project by Monday.

**Comment by smartITNinja** [comment]
You won't able to do wildcards with this package. It works (and will work) only with single domains.

This is because how the cert authority manages wildcarded cert renovations.

**Comment by archiebaer** [comment]
But it says it's supported. And Let's Encrypt supports it.

**Comment by archiebaer** [comment]
![image](https://user-images.githubusercontent.com/42045366/51787220-02924800-2167-11e9-916f-df4066dd6fcd.png)

**Comment by smartITNinja** [comment]
Sure, Let's Encrypt support wildcard certs.

I mean this package doesn't support this option. 

Renewing a wildcarded cert requires control over your DNS settings. This package will be unable to handle so many options successfully.

**Comment by archiebaer** [comment]
What about with this: https://www.npmjs.com/package/le-challenge-digitalocean. Seems to be built for it. Also, on NPM, it says greenlock supports wildcards.

**Comment by smartITNinja** [comment]
You will need a wrapper to perform DNS actions (if your DNS provider allows you).

But here's the real thing, even when this package's documentation states that wildcard is supported it's not accurate. 
What this package does is to create single certs based on a given list but no a wildcard cert.

This project has been moved here: [https://git.coolaj86.com/coolaj86/greenlock.js](url)

You can verify what I'm saying in these videos:
[https://www.youtube.com/watch?v=e8vaR4CEZ5s&list=PLZaEVINf2Bq_lrS-OOzTUJB4q3HxarlXk](url)
[https://www.youtube.com/watch?v=bTEn93gxY50&list=PLZaEVINf2Bq_lrS-OOzTUJB4q3HxarlXk&index=2](url)

I think you are just wasting your time here.

**Comment by archiebaer** [comment]
I'm not trying to make it work as I need. I'm trying to make it work how it says it should work. If it says it's supported, I'm not wasting my time by trying to use it that way.

**Comment by coolaj86** [comment]
Wildcards are supported by the framework, but it requires you to both use the APIs of your DNS provider as well as a storage plugin that supports wildcards.

The "dumb" filesystem approach won't work because you have a many-to-many relationship.

If you want to use Altnames (multiple domains per certificate), you need to use the `approveDomains` callback.

**Comment by coolaj86** [comment]
It turns out there was a bug in some of the wildcard handling.

I recently updated and re-arranged some of the dry-run tests that may have introduced the bug. It's fixed now.

**Comment by archiebaer** [comment]
Okay, the project I needed it for is dead now, but I'll certainly need wildcard certs in future. I just build a webserver with automatic ssl, and greenlock works seamlessly. Glad to know the bug has been fixed.

**Comment by archiebaer** [comment]
Still doesn't seem to work properly.

**Comment by archiebaer** [comment]
Here is the exact code I'm using:
```
const leChallengeDigitalOcean = require('le-challenge-digitalocean').create({
  debug: false,
  doApiKey: doApiKey
});
require('greenlock-express').create({
  email: adminEmail
, version: 'draft-11'
, agreeTos: true
, challengeType: 'dns-01'
, challenges: {
    'dns-01': leChallengeDigitalOcean
  }
, configDir: '~/.config/acme/'
, logRejectedDomains: false
, app: app
, approvedDomains: ["*." + domain, domain]
}).listen(80, 443, function () {
  console.log("Webserver is online.");
});
```
Same error as before. Also, as I previously said, I've spent hours googling for some examples with wildcards, and I can't find any. I assume I just put `*.domain.tld` in approvedDomains. I'm using the digitalocean dns plugin.

**Comment by archiebaer** [comment]
Oh, and if I swap `["*." + domain, domain]` to `[domain, "*." + domain]`, I don't get the error, but it doesn't seem to secure wildcards? I just get a "Secure connection failed" in my browser.

**Comment by archiebaer** [comment]
So a summary of what I've figured out so far is:
- If the wildcard is the first (or only, as it was in my original use case) item in the approvedDomains array, then it will not work. I can understand that it may have trouble setting the wildcard as the default domain for a certificate, But then:
- If the main domain is first, and the wildcard is after, it won't secure the wildcard. This puzzles me greatly. Also, I am sure of this, because I get `Fetching certificate for '[main domain]' to use as default for HTTPS server...` but no similar line for the wildcard. I would expect something like `Fetching certificate for '*.[main domain]' to use as default for HTTPS server...` to follow.

**Comment by archiebaer** [comment]
@solderjs Any updates on this issue?

**Comment by archiebaer** [comment]
Maybe it's because `_acme-challenge.*.[domain]` can't be a valid record.

**Comment by archiebaer** [comment]
How do DNS challenges handle that?

**Comment by archiebaer** [comment]
Also, turning on `logRejectedDomains` and `debug` provides this info:
```
[gl/index.js] tls SNI for 'abc.ziphost.online' rejected: not in list 'ziphost.online,*.ziphost.online' [ 'abc.ziphost.online' ] [ 'ziphost.online', '*.ziphost.online' ]
```
So I guess it's not treating * properly?

**Comment by solderjs** [comment]
Someone else brought a few places that I missed: https://git.coolaj86.com/coolaj86/greenlock-express.js/issues/43

Getting the json storage plugin is moving up higher on my priority list.

**Comment by archiebaer** [comment]
So this is a bug in Greenlock, not something I'm doing wrong?

**Comment by archiebaer** [comment]
Or is it an issue with DNS plugins?

**Comment by archiebaer** [comment]
If there's something I could patch right now with a module by going into node_modules, I'd rather do that than wait around for a few months.

**Comment by solderjs** [comment]
Let's move this discussion over to the real repo:

https://git.coolaj86.com/coolaj86/greenlock-express.js/issues/43#issuecomment-728

I've added some more detail.

**Comment by solderjs** [comment]
# Solved

https://git.coolaj86.com/coolaj86/greenlock-express.js/src/branch/master/examples/wildcard.js
