### ISSUE TITLE
greenlock.listen how to pass secureOptions (doc needed)

### ISSUE THREAD

**Issue by steamonimo** [Daplie/greenlock-express#133]
The https module has options to suppress TLS1.0 and older protocols.

const options = {secureOptions: constants.SSL_OP_NO_SSLv2 | constants.SSL_OP_NO_SSLv3 | constants.SSL_OP_NO_TLSv1 | constants.SSL_OP_NO_TLSv1_1};

These options can be passed: httpsModule.createServer( options, app );

How can these options be passed in greenlock.Create() ? Is there a parameter called options similar to app ? Would it be possible to add this parameter to Create ?

**Comment by solderjs** [comment]
This is the wrong repo. Let's continue the conversation over at: https://git.coolaj86.com/coolaj86/greenlock-express.js/issues

**Comment by steamonimo** [comment]
Thanks, will close issue here!
