### ISSUE TITLE
HELP WANTED: co-maintainers, tech support

### ISSUE THREAD

**Issue by coolaj86** [Daplie/greenlock-express#60]
I get a lot of bug requests that are purely due to misunderstanding.

I have a few that are so simple to fix (and have easy workarounds) that I just say "well, I'll get around to it sometime", but other things keep taking precedence.

Contact me aj@daplie.com if you have free cycles to help.

**Comment by Seikho** [comment]
Hey @coolaj86, I intend to lend a hand, but I suffer the same things as well. I'll shoot you an email shortly with how I'd like to contribute. Ideally to the lower level modules.

**Comment by jwulf** [comment]
Yo, I can help with documentation.

**Comment by coolaj86** [comment]
@jwulf Hit us up on mattermost.daplie.com (you can sign in with your git.daplie.com account). I've added you to the repo.
