### ISSUE TITLE
[STICKY] Unexpected duplicate key (le-store-certbot)

### ISSUE THREAD

**Issue by Dimtime** [Daplie/greenlock-express#81]
When sert create for test site i get this messages:

![93841dca-6620-11e6-8a89-37b80cf8c293](https://cloud.githubusercontent.com/assets/16452588/17825263/cbe0f7a2-666f-11e6-9df1-7be7e53094ef.jpg)

Site loading and seems work... but this messages confuse me... What wrong with them?

**Comment by coolaj86** [comment]
It's just a warning in [le-store-certbot](https://github.com/Daplie/le-store-certbot).

Ignore it.

**Comment by garenyondem** [comment]
I am getting the same error and it looks like it is renewing the certificates on each node restart. Can this be a case?

**Comment by coolaj86** [comment]
If it's renewing the cert on each restart it's likely that the directory where you're saving the certificates is being deleted or that your system clock is wrong (i.e. on a Raspberry Pi-like device with no RTC)
