### ISSUE TITLE
Some help with approveDomains cb

### ISSUE THREAD

**Issue by Dimtime** [Daplie/greenlock-express#82]
If check false what need write in cb ?

`cb(null, { options: opts, certs: certs });`

How redirect to error page for example? "Error: wrong url - no such domain exist"

Sorry maybe for silly question, but cant get how do it...

**Comment by Dimtime** [comment]
Or another solution... What write in cb: when url domain was wrong?

**Comment by coolaj86** [comment]
You must provide a certificate. There is no other non-error option.

By the nature of the problem any domain which resolves to the ip of your server can be validated, therefore a certificate can be issued.

If the domain cannot be resolved, then the SNI is being spoofed by an attacker.

**Comment by Dimtime** [comment]
Hm if i check domains and something go wrong... what better do - nothing then or what:
```
 if (opts.domains = my.domains) {  cb(null, { options: opts, certs: certs }); }
else {} //just nothing do?
```

**Comment by coolaj86** [comment]
Hey, sorry I forgot to respond. You callback with an error.

```
cb(new Error("domain not supported"));
```

**Comment by Dimtime** [comment]
"You callback with an error."

Some one more question, but where in code then i must try-catch it?

**Comment by polo2ro** [comment]
Hi, this is the issue i have too. i just see that i an error is provided to the callback, the module "le-sni-auto" output the error with console.error
https://github.com/Daplie/le-sni-auto/blob/master/index.js#L152

The error is then forwarded to another callback, i don't know yet where to catch it

**Comment by coolaj86** [comment]
Unfortunately you can't catch the error: https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener

The server just gracefully (?) kills the tls handshake and that's that.
