### ISSUE TITLE
le.challenges[http-01].loopback should be defined as function (opts, domain, token, keyAuthorization, cb) { ... }

### ISSUE THREAD

**Issue by reydelleon** [Daplie/greenlock-express#99]
Hi there,

After trying in vane to make this work with my project, I can only ask for help from you guys. I'm getting the error:

`le.challenges[http-01].loopback should be defined as function (opts, domain, token, keyAuthorization, cb) { ... } and should prove (by external means) that the ACME server challenge 'http-01' will succeed
`

This happens when I try to run my NodeJS app. 

This is how I'm configuring LE:

```
le.create({
    server: 'https://acme-v01.api.letsencrypt.org/directory', // in production use 'https://acme-v01.api.letsencrypt.org/directory'; for testing use 'staging'
    configDir: require('os').homedir() + '/letsencrypt',
    approvedDomains: function (opts, certs, cb) {
        opts.domains = certs && certs.altnames || opts.domains;
        opts.email = 'contact@myemail.me';
        opts.agreeTos = true;

        cb(null, { options: opts, certs: certs });
    }
});
```

And here is how I start the app:

```
var server = https.createServer(le.httpsOptions, le.middleware(app.callback()));
server.listen(443, function () {
    log.info(`Listening at https://${this.address}`);
});

var redirectHtpps = koa().use(koaSslify()).callback();
http.createServer(le.middleware(redirectHtpps)).listen(80, function () {
    log.info('handle ACME http-01 challenge and redirect to https');
});
```

You'll notice that I'm following the instructions on the readme as close as possible, yet the thing does work.

I should mention that I'm using MacOS for development. Are there any prerequisites for this code to work, outside of the code itself?

Thanks for your help before hand!

**Comment by insightfuls** [comment]
The message you're seeing is a harmless warning which will disappear in a future release. There should be no particular issues or special requirements for running it on Mac OS X. Have you tried visiting the domain being served, etc.? What error do you see in your browser or on the console when you do? To be able to satisfy the challenge issued by the ACME server, of course the machine must be public facing and have the relevant DNS records for the domain pointed to it.

**Comment by reydelleon** [comment]
Hey @insightfuls! Thanks for the very prompt response. I guess if that's the case, then the real error is this: 

```
var server = https.createServer(le.httpsOptions, le.middleware(app.callback()));

TypeError: le.middleware is not a function
    at Object.<anonymous> (/somepath/server.js:127:53)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
```

That is happening at the same time, but I though the latter was a consequence of the first one [which now I know is not an error], which takes place first. 

What can be happening here, then?

**Comment by reydelleon** [comment]
Uhmmm, I got it! Error on my side when creating the object. As you can see in the code above, I didn't assign the result of `le.create()`, and later on I use `le`, instead of the result of calling `create()` as I should have.

It's running now.
